---
name: 'Setup QtIFW'
description: 'Set up a specific version of QtIFW and add the command-line tools to the PATH.'
author: 'Julien Marrec, EffiBEM'
inputs:
  qtifw-version:
    description: "Version range or exact version of QtIFW version to use, using SemVer's version range syntax."
    default: '4.x'
outputs:
  qtifw-version:
    description: "The installed QtIFW version. Useful when given a version range as input."
  qtifw-bin-dir:
    description: "The bin directory (which is already added to your PATH) for debugging purposes."
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'code'
  color: 'blue'
