name: 'runtime-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:

  test: # make sure the action works on a clean machine without building
    runs-on: ${{ matrix.os }}
    strategy:
      # fail-fast: Default is true, switch to false to allow one platform to fail and still run others
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]
        qtifw-version: ['4.x', '4.6.1', '4.7.0', '4.8'] # '4.0.1']

    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          qtifw-version: ${{ matrix.qtifw-version }}

      - name: Test that the binaries are correctly added to path
        shell: bash
        run: |
          devtool --version
          which binarycreator
          ls -la $(which binarycreator)
